image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  - java -jar ./artifacts/app-ibank.jar -port=7777 -P:profile=test &gi

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true
